-- Fix newsletter_subscribers table security
CREATE POLICY "Only admins can view subscribers" 
ON public.newsletter_subscribers 
FOR SELECT 
USING (false);

CREATE POLICY "Only admins can update subscribers" 
ON public.newsletter_subscribers 
FOR UPDATE 
USING (false);

CREATE POLICY "Only admins can delete subscribers" 
ON public.newsletter_subscribers 
FOR DELETE 
USING (false);

-- Create profiles table
CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  username text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Profiles are viewable by owner" 
ON public.profiles FOR SELECT 
USING (auth.uid() = id);

CREATE POLICY "Profiles are editable by owner" 
ON public.profiles FOR UPDATE 
USING (auth.uid() = id);

CREATE POLICY "Profiles are insertable by self" 
ON public.profiles FOR INSERT 
WITH CHECK (auth.uid() = id);

-- Create calculator_history table
CREATE TABLE public.calculator_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  calculator_slug text NOT NULL,
  input_data jsonb,
  result_data jsonb,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.calculator_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can read own history" 
ON public.calculator_history FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "User can insert own history" 
ON public.calculator_history FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "User can delete own history" 
ON public.calculator_history FOR DELETE 
USING (auth.uid() = user_id);

-- Create favorites table
CREATE TABLE public.favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  calculator_slug text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  UNIQUE(user_id, calculator_slug)
);

ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "User can view own favorites" 
ON public.favorites FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "User can add favorites" 
ON public.favorites FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "User can remove favorites" 
ON public.favorites FOR DELETE 
USING (auth.uid() = user_id);

-- Create contact_messages table (public insert)
CREATE TABLE public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text NOT NULL,
  message text NOT NULL,
  submitted_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can submit contact form" 
ON public.contact_messages FOR INSERT 
WITH CHECK (true);

-- Create analytics_logs table
CREATE TABLE public.analytics_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users ON DELETE SET NULL,
  calculator_slug text,
  event_type text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.analytics_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can insert analytics events" 
ON public.analytics_logs FOR INSERT 
WITH CHECK (true);

-- Create trigger for updating profiles.updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_profiles_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

-- Create trigger to auto-create profile on user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id)
  VALUES (new.id);
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();